name: "conda setup"
description: "Prepare the conda environment"
runs:
  using: "composite"
  steps:
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Mambaforge
        activate-environment: pydfcsr
        use-mamba: true
        channels: conda-forge
    - name: Update environment
      shell: bash -l {0}
      run: mamba env update -n pydfcsr -f environment.yml
    - name: Install our Python package
      shell: bash -l {0}
      run: |
        pip install --no-dependencies .
    - name: Show the installed packages
      shell: bash -l {0}
      run: |
        conda list
