name: Publish Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: ${{ github.repository == 'ColwynGulliford/distgen' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.12"
          miniforge-version: latest
          channels: conda-forge
          activate-environment: distgen-dev
          environment-file: environment-dev.yml

      - name: Execute notebooks
        shell: bash -l {0}
        run: |
          pip install --no-dependencies .
          scripts/execute_notebooks.bash

      - name: Build Docs
        shell: bash -l {0}
        run: |
          mkdocs build
          zip -r distgen-examples.zip docs/examples/
          mv distgen-examples.zip ./site/assets/.

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/
